lchsiteam/lchs-go-pwa

.travis.yml
package.json
src/schedule/enums.ts
src/schedule/index.ts
src/schedule/schedules.ts
src/views/About.vue
src/views/Home.vue
vue.config.js

- Adds Travis CI to the project
- Some code cleanup

Stepping release 0.1.2

---

src/views/Settings.vue

it adds the GradeSelect class to the html elements and the GradeSelectItem to the html elements. It also textures the dropdowns with CSS to make them match more with the other buttons and the rest of the webpage.

Add CSS to the dropdown menus

---

src/schedule/index.ts

I forgot something, this will work this time

Updating the block days

---

src/themes.ts

[ft] Adds a new theme

---

src/schedule/index.ts
src/schedule/mdy_date.ts
src/schedule/schedules.ts
src/views/BellSchedule.vue
src/views/Home.vue
src/views/Now.vue
src/views/Welcome.vue
tslint.json

Mr. Clausen fix

---

src/schedule/index.ts
src/schedule/schedules.ts

does that and implements the new finals schedule

Implements block switch

---

src/schedule/index.ts
src/schedule/schedules.ts

i don't believe this is valid typescript

Revert "Implements block switch"

---

src/schedule/index.ts

To be clear, this is on 11/22/19 due to the turkey bowl.

Add 7/8 minimum day

---

docs/README.md

For some reason the image stopped existing.

[fix] Readme fix

---

src/schedule/index.ts

there are no block days next week so this gets rid of them in the code =D

Added the not-block days next week

---

docs/README.md
src/schedule/index.ts

Updates the readme and adds the block days that aren't there and makes them... "go away" *malicious smile.* is a gud

Develop > Master

---

package.json
public/index.html
src/views/BellSchedule.vue

Changing the version number cause we've been updating the app without changing the version number.

Fixing V-Calendar and Changing the Version Number

---

src/schedule/index.ts

This DOES NOT include SBAC because we don't know their schedule yet

Added all special dates through the end of Summer School

---

src/views/BellSchedule.vue
src/views/Now.vue
yarn.lock

This must be tweaked to make the update faster but still works.

Make it easier to switch grades

---

src/App.vue
src/store.ts
src/views/Now.vue
src/views/Settings.vue

Notifications cus Devyn wanted me to publish it for something.
Please don't kill me, I couldn't get my local fork working properly, sorry for the branch.

Notifications pls dont kill me

---

src/schedule/enums.ts
src/schedule/index.ts
src/schedule/schedules.ts
src/views/BellSchedule.vue
src/views/Home.vue
src/views/Now.vue
src/views/Settings.vue

=D
Also added a wee bit of text that says we have an extention

Updated schedules for 2020 and Added Elementary Support

---

src/schedule/index.ts
src/views/BellSchedule.vue
src/views/Now.vue

also i added plusDays and plusMins again for debugging

[fix] fixed multiple periods being highlighted if they had same name

---

package.json
public/index.html
src/App.vue
src/localStorage.ts
src/registerServiceWorker.ts
src/schedule/index.ts
src/views/Now.vue
src/views/Settings.vue

Please test every change I made, let's be sure that this doesn't break anything.

Style and Notification improvements

---

src/schedule/schedules.ts

[HF] Updated block schedule so no school ends at the right time

---

src/App.vue
src/changelog/v0.1.3.ts
src/views/Now.vue

Just some housekeeping

---

src/views/Now.vue

Ok after this now we can merge to master from develop. :)

Fixed Border rgba

---

src/schedule/enums.ts
src/schedule/index.ts
src/schedule/schedules.ts

Reverts lchsiteam/lchs-go-pwa#306

Revert "temporary first day of school fix"

---

src/schedule/enums.ts
src/schedule/index.ts
src/schedule/schedules.ts

Reverts lchsiteam/lchs-go-pwa#307

Revert "Testing > develop"

---

src/schedule/enums.ts
src/schedule/index.ts
src/schedule/schedules.ts

Reverts lchsiteam/lchs-go-pwa#305

Revert "Ninth Grade Registration Event Schedule"

---

src/schedule/index.ts

Reverts lchsiteam/lchs-go-pwa#304

Revert "Develop > Master"

---

src/schedule/index.ts

Reverts lchsiteam/lchs-go-pwa#303

Revert "[HF] summer school dates"

---

src/schedule/index.ts

Reverts lchsiteam/lchs-go-pwa#317

Revert "hopefully this works"

---

src/schedule/index.ts

Reverts lchsiteam/lchs-go-pwa#315

Revert "Revert "[HF] summer school dates""

---

src/schedule/index.ts

Reverts lchsiteam/lchs-go-pwa#314

Revert "Revert "Develop > Master""

---

src/schedule/enums.ts
src/schedule/index.ts
src/schedule/schedules.ts

Reverts lchsiteam/lchs-go-pwa#313

Revert "Revert "Ninth Grade Registration Event Schedule""

---

src/schedule/enums.ts
src/schedule/index.ts
src/schedule/schedules.ts

Reverts lchsiteam/lchs-go-pwa#312

Revert "Revert "temporary first day of school fix""

---

src/schedule/enums.ts
src/schedule/index.ts
src/schedule/schedules.ts

Reverts lchsiteam/lchs-go-pwa#311

Revert "Revert "Testing > develop""

---

src/views/Credits.vue

Develop --> Master

---

src/schedule/index.ts

oh yea also clean up schedules

honor thy veterans y'all

---

src/schedule/index.ts

Add all breaks for 2023-2024 school year

---

src/App.vue
src/store.ts

will merge when everything is ready to migrate

add migration message
